steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE}:${SHORT_SHA}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}:${SHORT_SHA}']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'container', 'clusters', 'get-credentials',
      '${_CLUSTER}',
      '--region', '${_REGION}',
      '--project', '${PROJECT_ID}'
    ]

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/microservice-deployment'
      - 'microservice=${_IMAGE}:${SHORT_SHA}'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
      - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'

images:
  - '${_IMAGE}:${SHORT_SHA}'

substitutions:
  _IMAGE: "us-central1-docker.pkg.dev/my-gke-cloudsql-demo-ruen/my-microservice-repo/microservice"
  _REGION: "us-central1"
  _CLUSTER: "my-gke-cluster"
  PROJECT_ID: "my-gke-cloudsql-demo-ruen"

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY

