steps:
- name: 'gcr.io/cloud-builders/docker'
args: ['build', '-t', '${_IMAGE}:${SHORT_SHA}', '.']
- name: 'gcr.io/cloud-builders/docker'
args: ['push', '${_IMAGE}:${SHORT_SHA}']
- name: 'gcr.io/cloud-builders/kubectl'
args:
- 'set'
- 'image'
- 'deployment/microservice-deployment'
- 'microservice=${_IMAGE}:${SHORT_SHA}'
env:
- 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
- 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'


images:
- '${_IMAGE}:${SHORT_SHA}'


substitutions:
_IMAGE: "$IMAGE_URI"
_REGION: "$REGION"
_ZONE: "$ZONE"


timeout: '1200s'
